### ISSUE TITLE
TypeError: __new__() takes exactly 3 arguments (2 given)

### ISSUE THREAD

**Issue by codewithpassion** [amperka/ino#103]
Hi

I'm trying to run ino on a Ubuntu BeagleBone with Python 2.7.5. 
But I get a TypeError. See the Traceback below.

Any idea what's wrong?

Thanks Dominik

Traceback (most recent call last):
  File "/usr/local/bin/ino", line 6, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/ino/runner.py", line 63, in main
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/ino/commands/build.py", line 205, in run
    self.discover()
  File "/usr/local/lib/python2.7/dist-packages/ino/commands/build.py", line 52, in discover
    ['Arduino.h'] if self.e.arduino_lib_version.major else ['WProgram.h'], 
  File "/usr/local/lib/python2.7/dist-packages/ino/environment.py", line 273, in arduino_lib_version
    v = Version.parse(v_string)
  File "/usr/local/lib/python2.7/dist-packages/ino/environment.py", line 44, in parse
    return cls(*map(int, v.split('.')))
TypeError: **new**() takes exactly 3 arguments (2 given)

**Comment by nkrkv** [comment]
Hmmm... Looks like unexpected version string in `version.txt` file in Arduino IDE. Can you provide its content?

**Comment by BrianAdams** [comment]
The version.txt has:
1:1.0.5+dfsg2-1

**Comment by laptop006** [comment]
I've got a patch for this, but it seems like there's more cleanups needed to run on the current Debian, I'll finish the getting it working and send a complete patch.

**Comment by nkrkv** [comment]
Fixed in 0.3.6
