### ISSUE TITLE
ino build fails on Arch Linux

### ISSUE THREAD

**Issue by Bouni** [amperka/ino#184]
Hi,

I've updated may arch linux a few days ago and as far as I remember ino was updated, too.

Currently i use the version **aur/ino-git 20140415-1** in combination with arduino **aur/arduino 1:1.0.5-6** on **Arch Linux 3.15.5-1-ARCH**.

My problem is that when I try to build my project using the command **ino build**, I get this error message:

```
Traceback (most recent call last):
  File "/usr/bin/ino", line 6, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/ino/runner.py", line 76, in main
    args.func(args)
  File "/usr/lib/python2.7/site-packages/ino/commands/build.py", line 283, in run
    self.discover(args)
  File "/usr/lib/python2.7/site-packages/ino/commands/build.py", line 123, in discover
    core_place = os.path.join(board['_coredir'], 'cores', board['build']['core'])
KeyError: '_coredir'
```

Before I've updated, I was able to build my project.
Has anybody an idea what i can do to solve this issue?

**Comment by byteofsoren** [comment]
I have had lots off problem setting up ino on my arch.
The first thing I did to solve my problem was to sett the PYTHONPATH environment variable.

```
export PYTHONPATH='/usr/local/lib/python2.7/site-packages/:/usr/lib/python3.4/site-packages/'
```

Not sure if that helps you, but maybe it helps some other one. :)

# 

p.s if you get this error form `ino upload`

```
Searching for avrdude.conf ... FAILED
avrdude.conf not found. Searched in following places: 
  - /usr/local/share/arduino/hardware/tools
  - /usr/share/arduino/hardware/tools
  - /etc/avrdude
```

do this.

```
$ sudo mkdir /etc/avrdude
$ sudo ln -s /etc/avrdude.conf /etc/avrdude/avrdude.conf
```

**Comment by Bouni** [comment]
I don't get any errors using the **aur/ino**, but as soon as i install **aur/ino-git** i get the error described above. So I'm or less sure that it's not a python version related issue.

But anyway, thanks for the feedback!

**Comment by chennes** [comment]
For what it's worth, I'm seeing the same error on OS X Yosemite with the git version. Installing via Homebrew works fine.
