### ISSUE TITLE
[Windows] Build fails

### ISSUE THREAD

**Issue by iarspider** [amperka/ino#26]
After fixing the issue #25 (unable to find avr-gcc), I tried to build some code, but got this:
`Traceback (most recent call last):
  File "D:\Work\arduino-1.0\ino-0.3.3\bin\run.py", line 6, in <module>
    main()
  File "C:\Python27\lib\site-packages\ino-0.3.3-py2.7.egg\ino\runner.py", line 63, in main
    args.func(args)
  File "C:\Python27\lib\site-packages\ino-0.3.3-py2.7.egg\ino\commands\build.py", line 189, in run
    self.make('Makefile.sketch')
  File "C:\Python27\lib\site-packages\ino-0.3.3-py2.7.egg\ino\commands\build.py", line 138, in make
    makefile = self.render_template(makefile + '.jinja', makefile, **kwargs)
  File "C:\Python27\lib\site-packages\ino-0.3.3-py2.7.egg\ino\commands\build.py", line 130, in render_template
    contents = template.render(**ctx)
  File "C:\Python27\lib\site-packages\jinja2-2.6-py2.7.egg\jinja2\environment.py", line 894, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Python27\lib\site-packages\ino-0.3.3-py2.7.egg\ino\commands\..\make\Makefile.sketch.jinja", line 4, in top-level template code
    {% set sketches = e.src_dir|glob('*.pde', '*.ino')|filemap(src_build_dir, e.names.cpp) %}
  File "C:\Python27\lib\site-packages\ino-0.3.3-py2.7.egg\ino\filters.py", line 39, in glob
    for entry in os.listdir(scan_dir):
WindowsError: [Error 3] The system cannot find the path specified: 'src\\*.*'
`

**Comment by nkrkv** [comment]
Are you in a directory that was filled with project skeleton after `ino init`? In other words: do you actually have `src` subdir in current directory?

**Comment by iarspider** [comment]
Ah, I must have missed the quickstart part.

**Comment by iarspider** [comment]
`

> python d:\uno init -t Blink
> 
> python d:\uno build -d d:\Work\arduino-1.0

Searching for Board description file (boards.txt) ... ←[92md:\Work\arduino-1.0\hardware\arduino\boards.txt←[0m
Searching for Arduino lib version file (version.txt) ... ←[92md:\Work\arduino-1.0\lib\version.txt←[0m
Detecting Arduino software version ...  ←[92m1.0 (1.0)←[0m
Searching for Arduino core library ... ←[92md:\Work\arduino-1.0\hardware\arduino\cores\arduino←[0m
Searching for Arduino standard libraries ... ←[92md:\Work\arduino-1.0\libraries←[0m
Searching for Arduino variants directory ... ←[92md:\Work\arduino-1.0\hardware\arduino\variants←[0m
Searching for avr-gcc ... ←[92md:\Work\arduino-1.0\hardware\tools\avr\bin\avr-gcc←[0m
Searching for avr-g++ ... ←[92md:\Work\arduino-1.0\hardware\tools\avr\bin\avr-g++←[0m
Searching for avr-ar ... ←[92md:\Work\arduino-1.0\hardware\tools\avr\bin\avr-ar←[0m
Searching for avr-objcopy ... ←[92md:\Work\arduino-1.0\hardware\tools\avr\bin\avr-objcopy←[0m
Traceback (most recent call last):
  File "D:\run.py", line 6, in <module>
    main()
  File "C:\Python27\lib\site-packages\ino-0.3.3-py2.7.egg\ino\runner.py", line 6
3, in main
    args.func(args)
  File "C:\Python27\lib\site-packages\ino-0.3.3-py2.7.egg\ino\commands\build.py"
, line 189, in run
    self.make('Makefile.sketch')
  File "C:\Python27\lib\site-packages\ino-0.3.3-py2.7.egg\ino\commands\build.py"
, line 139, in make
    ret = subprocess.call(['make', '-f', makefile, 'all'])
  File "C:\Python27\lib\subprocess.py", line 493, in call
    return Popen(_popenargs, *_kwargs).wait()
  File "C:\Python27\lib\subprocess.py", line 679, in **init**
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 893, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified
`

**Comment by iarspider** [comment]
I guess it doesn't find make.exe (part of Arduino IDE/avr-gcc)

**Comment by nkrkv** [comment]
Yes, it's a continue of issue #25. `make` is not found. To continue the battle you could replace

```
ret = subprocess.call(['make', '-f', makefile, 'all'])
```

with something like

```
ret = subprocess.call(['d:\full\path\to\make.exe', '-f', makefile, 'all'])
```

**Comment by iarspider** [comment]
Well, that is even uglier than in issue 25. The best way to handle this would be to alter %PATH% variable before calling make - this will help make find the rest of the tools.

**Comment by nkrkv** [comment]
I'm not consider to include these hacks as is. I suggest just to find all corner stones on Windows so that they could be carefully worked around eventually.

**Comment by iarspider** [comment]
Another bump in the road: windows doesn't need '-p' in mkdir to create parent dirs automaticaly (with 'command extenstions' enabled - i.e. WinXP or newer, maybe Win2000), and echo doesn't need '-n'. And Windows have no built-in 'cat' (but arduino has it)

**Comment by iarspider** [comment]
`Linking firmware.elf
d:\Work\arduino-1.0\hardware\tools\avr\bin\avr-gcc.exe -Os -Wl,--gc-sections -mmcu=atmega328p -o .build\firmware.elf 
.build\src\sketch.o -lmd:/work/arduino-1.0/hardware/tools/avr/bin/../lib/gcc/avr/4.3.2/../../../../avr/lib/avr5/crtm328p.o:(.init9+0x0): undefined reference to``main'
make: *** [.build\firmware.elf] Error 1
Make failed with code 2
`
For some reason, main.cpp et al are not added as dependencies under Windows.

**Comment by iarspider** [comment]
Found the source of the problem. I will now cleanup my hacks and make a pull request.

**Comment by amoose136** [comment]
> `` Linking firmware.elf d:\Work\arduino-1.0\hardware\tools\avr\bin\avr-gcc.exe -Os -Wl,--gc-sections -mmcu=atmega328p -o .build\firmware.elf .build\src\sketch.o -lmd:/work/arduino-1.0/hardware/tools/avr/bin/../lib/gcc/avr/4.3.2/../../../../avr/lib/avr5/crtm328p.o:(.init9+0x0): undefined reference to``main' make: *** [.build\firmware.elf] Error 1 Make failed with code 2 ``
> For some reason, main.cpp et al are not added as dependencies under Windows.

This is currently where my build of ino gets to. 
> Found the source of the problem. I will now cleanup my hacks and make a pull request.

Were you ever able to solve the main.cpp issue? I looked through the 4 commits you made on your fork and I couldn't see any changes that seemed relevant to that issue.

**Comment by amoose136** [comment]
Specifically I am running an install on python3 with MSYS2 and I get this:
```bash
blink ❯ ino build -v -m uno
*** RUN .build_msys/uno/Makefile.sketch ...
*** RUN .build_msys/uno/Makefile.deps ...
*** RUN .build_msys/uno/Makefile ...
Linking firmware.elf
../../../../Progra~2/Arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega328p -Wl,-Os -Wl,--gc-sections -o .build_msys/uno/firmware.elf .build_msys/uno/src/sketch.o -lm
c:/progra~2/arduino/hardware/tools/avr/bin/../lib/gcc/avr/5.4.0/../../../../avr/lib/avr5/crtatmega328p.o:(.init9+0x0): undefined reference to `main'
collect2.exe: error: ld returned 1 exit status
make: *** [.build_msys/uno/Makefile:42: .build_msys/uno/firmware.elf] Error 1
Make failed with code 2
```
