### ISSUE TITLE
Issue running 'ino --help' after fresh install (pip install ino)

### ISSUE THREAD

**Issue by ttambow** [amperka/ino#278]
```
bash~$ ino --help
Traceback (most recent call last):
  File "/home/tblakel/anaconda3/bin/ino", line 3, in <module>
    from ino.runner import main
  File "/home/tblakel/anaconda3/lib/python3.6/site-packages/ino/runner.py", line 78
    print colorize(str(exc), 'red')
                 ^
SyntaxError: invalid syntax

```

Running on...

```
bash~$ uname -a
Linux Mint-ThinkCentre-M57 4.13.0-37-generic #42~16.04.1-Ubuntu SMP Wed Mar 7 16:03:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by jieyouxu** [comment]
`pip` seems to be aliased to pip 3; first uninstall ino then try `pip2 install ino`.
