### ISSUE TITLE
Build failed with IDE1.0

### ISSUE THREAD

**Issue by ilovemistakes** [amperka/ino#29]
$ ino init -t blink
$ ino build -m mega -d ~/arduino-1.0/
Searching for Arduino lib version file (version.txt) ... /home/ilovemistakes/arduino-1.0/lib/version.txt
Detecting Arduino software version ...  1.0 (1.0)
Searching for Arduino core library ... /home/ilovemistakes/arduino-1.0/hardware/arduino/cores/arduino
Searching for Arduino standard libraries ... /home/ilovemistakes/arduino-1.0/libraries
Searching for Arduino variants directory ... /home/ilovemistakes/arduino-1.0/hardware/arduino/variants
Searching for avr-gcc ... /usr/bin/avr-gcc
Searching for avr-g++ ... /usr/bin/avr-g++
Searching for avr-ar ... /usr/bin/avr-ar
Searching for avr-objcopy ... /usr/bin/avr-objcopy
Traceback (most recent call last):
  File "/usr/local/bin/ino", line 5, in <module>
    pkg_resources.run_script('ino==0.3.3', 'ino')
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 467, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 1200, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.6/dist-packages/ino-0.3.3-py2.6.egg/EGG-INFO/scripts/ino", line 6, in <module>
    main()
  File "/usr/local/lib/python2.6/dist-packages/ino-0.3.3-py2.6.egg/ino/runner.py", line 63, in main
    args.func(args)
  File "/usr/local/lib/python2.6/dist-packages/ino-0.3.3-py2.6.egg/ino/commands/build.py", line 187, in run
    self.setup_flags(args.board_model)
  File "/usr/local/lib/python2.6/dist-packages/ino-0.3.3-py2.6.egg/ino/commands/build.py", line 98, in setup_flags
    board['build']['variant'])
KeyError: 'variant'

$ ls /home/ilovemistakes/arduino-1.0/hardware/arduino/variants
eightanaloginputs  leonardo  mega  micro  standard

I am not able to build any project on Ubuntu 10.10 32-bit with Arduino IDE 1.0.

**Comment by ilovemistakes** [comment]
Ok, i got it. Board model list is cached in .build/environment.pickle . When i first ran "ino list-models", it found stale boards.txt in /usr/share/arduino/ and cached the list. Even if i specify "-d", it still tries to use old boards list. When removed .build/environment.pickle , build succeeded. Maybe per-arduino-directory cache required?

**Comment by nkrkv** [comment]
Yes, you're right. Thanks for the report. Actually there are few other bugs related to a dirty cache. Will fix'em eventually.
