### ISSUE TITLE
ino lib installing to wrong place in OS X lion

### ISSUE THREAD

**Issue by Tylerc230** [amperka/ino#31]
I'm installing ino by cloning the github repo and running 'make install'.  It appears to install the lib files at '/usr/local/lib/python2.7/site-packages/ino'.  When I run:
 `ino build`, I get:
`Traceback (most recent call last):
  File "/usr/local/bin/ino", line 3, in <module>
    from ino.runner import main
ImportError: No module named ino.runner`

I believe the correct place to install would be `/Library/Python/2.7/site-packages/ino`
If I'm in error please let me know the correct procedure to install on OSX; I'm not terribly knowledgable of python. Thanks.

**Comment by sibblegp** [comment]
Same issue.

**Comment by prashanta** [comment]
Same problem here on OS X Lion. Installing with python worked.

**Comment by dragonszy** [comment]
'python setup.py install' works for mountain lion, if there is permission limit, add sudo ahead.

**Comment by samura** [comment]
@dragonszy thank you. does the trick

**Comment by mynamewastaken** [comment]
Edit again:

For those googling, my error message on Linux Mint was:
`Traceback (most recent call last):
  File "/usr/local/bin/ino", line 3, in <module>
    from ino.runner import main
ImportError: No module named ino.runner`

I've tried installing both from github and pip/easy_install. In all cases, I get the same error as OP. However, I'm on Linux Mint. The path is correct, but permissions somewhere, aren't correct. I can then only run `ino` related commands as root or with sudo. Is there an easy way to let any user access `ino` without root permissions?

After some more digging: the `staff` group appears (at least on my Linux Mint system) to only be used in `/usr/local/lib/python2.7/dist-packages` directory. You should be able to run `ino` without additional privileges if you add yourself to the `staff` group. Not sure why it's setup like this. Could be Mint, Debian, Ubuntu, Python, or `ino` being strange..

**Comment by translucide** [comment]
Instructions from :
http://inotool.org/#installation  and http://inotool.org/quickstart

This is what I did to install ino in $HOME/Arduino/.tools
1. Run this shell script (for Fedora) in terminal. Package names might differ in a different linux distribution

#!/bin/sh
su -c "yum install picocom python-configobj python-jinja2 pyserial"
su -c "yum groupinstall \"Development Tools\" \"Development Libraries\""
mkdir $HOME/Arduino
mkdir $HOME/Arduino/.tools
cd $HOME/Arduino
git clone git://github.com/amperka/ino.git
cd ino
make install DESTDIR=~/Arduino/.tools PREFIX=/ino
cd ../
rm -R -f ./ino
1. Modify the /bin/ino file so it stops complaining about damn ino.runner :
   ~/Arduino/.tools/ino/bin/ino, 2nd line add :
   import sys;
   sys.path.append("/home/<user name here>/Arduino/.tools/ino/lib/python2.7/site-packages")

Hope it is helpful to others that want to use a custom path for that tool so it stays in my home folder and remains when I format the system partition to upgrade!

I have not tested everything, just the project creation, compiling and uploading process. They all work !

**Comment by translucide** [comment]
Staff group does not exists on fedora not are files owned by staff so on Fedora the previous comment does not apply.

**Comment by horchler** [comment]
This is still an issue with 0.3.7 and OS X Mavericks. The documentation and/or Makefile seems to still not have been updated. `sudo python setup.py install` seems to fix it. Also, the Makefile refers to `python2` – there is no `python2` by default on OS X. There's probably a better way to specify that you want 2.6+. At least the documentation should mention that the user may need to modify this.
