### ISSUE TITLE
Board description file (boards.txt) not found.

### ISSUE THREAD

**Issue by xiujunma** [amperka/ino#71]
```
Searching for Board description file (boards.txt) ... FAILED
Board description file (boards.txt) not found. Searched in following places: 
  - /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino
  - /usr/local/share/arduino/hardware/arduino
  - /usr/share/arduino/hardware/arduino
```

I'm using Arduino 1.5.2 beta, boards.txt is placed in /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino/avr/boards.txt.

**Comment by yosemitebandit** [comment]
@xiujunma -- I had that problem as well.  The [fork from rogue-hack-lab](https://github.com/rogue-hack-lab/ino) worked for me.

**Comment by xiujunma** [comment]
Thank you for sharing, I will try it later.

**Comment by insanity54** [comment]
I have this same problem and the fork from rogue-hack-lab did not solve the problem for me.

The issue for me was that my arduino files are in my home directory, and ino is not programmed to look for arduino files there. This solved the issue for me:

```
sudo cp -r ~/arduino-1.0.5 /usr/local/share/arduino
```

**Comment by lgruen** [comment]
If you're using Ubuntu or similar, "sudo apt-get install arduino" might do the trick alternatively.

**Comment by chrisspen** [comment]
@Igruen, The arduino package in the standard repo is ancient. I don't recommend using that unless it's absolutely necessary.

**Comment by chrisspen** [comment]
@insanity54 Note this won't work for the new arduino 1.5+ release. The folder structure is different, which ino apparently does not support. e.g. `hardware/arduino/boards.txt` is now at `hardware/arduino/avr/boards.txt`.

**Comment by AndyCross** [comment]
Is there a way to get ino to work with 1.5.8 BETA? I'm looking to use this with a Due board. Is 1.5.8 required for ino, or just the IDE?

**Comment by tonyc** [comment]
I'm running into this as well, on OSX. Anyone have some ideas?

**Comment by craigbeck** [comment]
+1 on OS X

```
$ ino build
Searching for Board description file (boards.txt) ... FAILED
Board description file (boards.txt) not found. Searched in following places: 
  - /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino
  - /usr/local/share/arduino/hardware/arduino
  - /usr/share/arduino/hardware/arduino
```

searching for `boards.txt`:

```
$ find /Applications/Arduino.app -iname boards.txt
/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/boards.txt
/Applications/Arduino.app/Contents/Java/hardware/arduino/sam/boards.txt
```

It look like [this code](https://github.com/amperka/ino/blob/master/ino/environment.py#L215-L222) indicates it _should_ find boards.txt under the `avr/` directory but my install is not.

**Comment by marcu** [comment]
Install the Arduino IDE version 1.0.x and the problem is resolved.

**Comment by letterj** [comment]
Using the latest arduino version 1.6.3.  on Mac System Version: OS X 10.10.3 (14D136)
Searching for Board description file (boards.txt) ... FAILED
Board description file (boards.txt) not found. Searched in following places:
- /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino
- /usr/local/share/arduino/hardware/arduino
- /usr/share/arduino/hardware/arduino

The file is actually located at /Application/Arduino.app/Contents/Java/hardware/arduino/avr/boards.txt

**Comment by chrisspen** [comment]
I just ran into this error again on a fresh install. Is inotools a dead project? I tried submitting a patch and it's been ignored. That's really frustrating, because inotools is infinitely easier to use than the horrible Arduino Gui.

**Comment by rsrini7** [comment]
Hi chrisspen ,
I have replaced your environment.py and i am getting below error. Any suggestion ?
make: execvp: /bin/sh: Argument list too long
.build/uno/Makefile.deps:14: recipe for target '.build/uno/src/sketch.d' failed
make: **\* [.build/uno/src/sketch.d] Error 127
Make failed with code 2

I am getting below error for the actual environment.py:

Searching for Board description file (boards.txt) ... /usr/local/share/arduino/hardware/arduino/boards.txt
Traceback (most recent call last):
  File "/usr/local/bin/ino", line 6, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/ino/runner.py", line 64, in main
    e.process_args(args)
  File "/usr/local/lib/python2.7/dist-packages/ino/environment.py", line 263, in process_args
    all_models = self.board_models()
  File "/usr/local/lib/python2.7/dist-packages/ino/environment.py", line 204, in board_models
    subdict[key] = {}
TypeError: 'str' object does not support item assignment
ino build returned 256
127.0.0.1 - - [13/Jun/2015 06:49:56] "POST / HTTP/1.1" 400 -

**Comment by ErichBSchulz** [comment]
@lgruen - your trick worked for me thx

Having to install an old package when you've already got the latest install in your system isn't ideal tho...

**Comment by rajanjamu** [comment]
Any workarounds for this? I am also facing the same issue. I don't want to go back to previous version (1.0.6) when 1.6.x is available.

**Comment by letterj** [comment]
I put together this pull request a while back to that fixed my issues with 1.6.3 

https://github.com/amperka/ino/pull/246

**Comment by tedrobotbuilder** [comment]
from the menu: Window/Preferences set the Arduino IDE path to your install of the Arduino IDE nomrally C:\Program Files\Arduino

**Comment by antonbrams** [comment]
i have also this issue... and i think, i should download a regular Arduino App to my Mac to have those Board Libs, am i right? or can i just download this files from internet separatly?

**Comment by trevery** [comment]
Searching for Board description file (boards.txt) ... FAILED
Board description file (boards.txt) not found. Searched in following places: 
  - /Applications/Arduino.app/Contents/Java/hardware/arduino
  - /Applications/Arduino.app/Contents/Resources/Java/hardware/arduino
  - /usr/local/share/arduino/hardware/arduino
  - /usr/share/arduino/hardware/arduino

I add the true dir, but the bug still exists.
