### ISSUE TITLE
Ino fails to upload on NixOS

### ISSUE THREAD

**Issue by the-kenny** [amperka/ino#83]
Building works fine, and the firmware.elf is generated in the correct directory (=.build/uni/firmware.hex/.elf=). Here's the output:

```
arduino:[moritz@moritz-x230:/tmp/foo]$ ino upload
Searching for stty ... /nix/store/k0kd4brqjm1017bhyj8rkyy36n0v5kmh-coreutils-8.21/bin/stty
Searching for avrdude ... /nix/store/p6n5z1rq39nb8l8zax4y568vivh8api3-arduino-core/share/arduino/hardware/tools/avrdude
Searching for avrdude.conf ... /nix/store/p6n5z1rq39nb8l8zax4y568vivh8api3-arduino-core/share/arduino/hardware/tools/avrdude.conf
Guessing serial port ... /dev/ttyUSB0
Traceback (most recent call last):
  File "/nix/store/wbas8484arqww18gxgn0mn7hd8dq35m2-ino-0.3.5/bin/.ino-wrapped", line 5, in <module>
    pkg_resources.run_script('ino==0.3.5', 'ino')
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 489, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 1207, in run_script
  File "/nix/store/wbas8484arqww18gxgn0mn7hd8dq35m2-ino-0.3.5/lib/python2.7/site-packages/ino-0.3.5-py2.7.egg/EGG-INFO/scripts/ino", line 6, in <module>
    main()
  File "/nix/store/wbas8484arqww18gxgn0mn7hd8dq35m2-ino-0.3.5/lib/python2.7/site-packages/ino-0.3.5-py2.7.egg/ino/runner.py", line 63, in main
    args.func(args)
  File "/nix/store/wbas8484arqww18gxgn0mn7hd8dq35m2-ino-0.3.5/lib/python2.7/site-packages/ino-0.3.5-py2.7.egg/ino/commands/upload.py", line 130, in run
    '-U', 'flash:w:%s:i' % self.e['hex_path'],
  File "/nix/store/yzj6p5f7iyh247pwxrg97y3klm6d0cni-python-2.7.3/lib/python2.7/subprocess.py", line 493, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/nix/store/yzj6p5f7iyh247pwxrg97y3klm6d0cni-python-2.7.3/lib/python2.7/subprocess.py", line 679, in __init__
    errread, errwrite)
  File "/nix/store/yzj6p5f7iyh247pwxrg97y3klm6d0cni-python-2.7.3/lib/python2.7/subprocess.py", line 1249, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by the-kenny** [comment]
Nevermind - I think I've found the problem. It wasn't ino-related.
