### ISSUE TITLE
Can't build sketch on Kali Linux!?

### ISSUE THREAD

**Issue by DarkXDroid** [amperka/ino#88]
Here's my problem!

I run the command: "ino init -t blink" then I proceed to run "ino build -m atmega328 0r ino build --board-model atmega328 -d /root/arduino-1.0.5" 

But I get this error:

"Detecting Arduino software version ... 
Traceback (most recent call last):
  File "/usr/local/bin/ino", line 5, in <module>
    pkg_resources.run_script('ino==0.3.5', 'ino')
  File "/usr/local/lib/python2.7/dist-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 489, in run_script
    yield ep
  File "/usr/local/lib/python2.7/dist-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 1207, in run_script

  File "/usr/local/lib/python2.7/dist-packages/ino-0.3.5-py2.7.egg/EGG-INFO/scripts/ino", line 6, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/ino-0.3.5-py2.7.egg/ino/runner.py", line 63, in main
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/ino-0.3.5-py2.7.egg/ino/commands/build.py", line 205, in run
    self.discover()
  File "/usr/local/lib/python2.7/dist-packages/ino-0.3.5-py2.7.egg/ino/commands/build.py", line 52, in discover
    ['Arduino.h'] if self.e.arduino_lib_version.major else ['WProgram.h'], 
  File "/usr/local/lib/python2.7/dist-packages/ino-0.3.5-py2.7.egg/ino/environment.py", line 273, in arduino_lib_version
    v = Version.parse(v_string)
  File "/usr/local/lib/python2.7/dist-packages/ino-0.3.5-py2.7.egg/ino/environment.py", line 44, in parse
    return cls(*map(int, v.split('.')))
TypeError: **new**() takes exactly 3 arguments (2 given)"

It's worth mention that Kali Linux has a Arduino IDE already installed in /usr/share/arduino/, is there some kind of conflict? The only thing I needed to install was "picocom"

I installed ino from source with setup_install and tried installing it via "pip install ino" both succeeded

**Comment by nkrkv** [comment]
Fixed in 0.3.6
