### ISSUE TITLE
raspberry pi can't upload to leonardo

### ISSUE THREAD

**Issue by i-make-robots** [amperka/ino#90]
t@raspberrypi:~/beep# ino upload -m leonardo
Guessing serial port ... /dev/ttyACM0
Traceback (most recent call last):
  File "/usr/local/bin/ino", line 5, in <module>
    pkg_resources.run_script('ino==0.3.5', 'ino')
  File "build/bdist.linux-armv6l/egg/pkg_resources.py", line 509, in run_script
  File "build/bdist.linux-armv6l/egg/pkg_resources.py", line 1397, in run_script
  File "/usr/local/lib/python2.7/dist-packages/ino-0.3.5-py2.7.egg/EGG-INFO/scripts/ino", line 6, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/ino-0.3.5-py2.7.egg/ino/runner.py", line 63, in main
    args.func(args)
  File "/usr/local/lib/python2.7/dist-packages/ino-0.3.5-py2.7.egg/ino/commands/upload.py", line 72, in run
    s.setDTR(False)
  File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 534, in setDTR
    fcntl.ioctl(self.fd, TIOCMBIC, TIOCM_DTR_str)
IOError: [Errno 32] Broken pipe

no amount of pressing reset matters.  rebooting raspberry pi makes no difference.  disconnecting everything and restarting makes no difference.  beep sketch compiles without error (ino build -m leonardo).  sketch uploads fine to UNO.  I need a device that doesn't reset every time serial connection is opened. :T
What do?

**Comment by ajford** [comment]
Have you tried holding the reset button down until after you started the upload? According to the Arduino page on the Leonardo, because the Leonardo does not use a a dedicated chip for serial comms, the serial port is created during the bootloader startup, then destroyed afterwards. This may cause timing issues, so the Arduino page recommends holding the reset button down until after the software says it starts uploading.

http://arduino.cc/en/Guide/ArduinoLeonardoMicro?from=Guide.ArduinoLeonardo#toc12

**Comment by bendenoz** [comment]
Hi, I have the exact same problem with and arduino micro.
Not heavily tested, but the patch below is currently working for me. Basically DTR should not be reset for those boards, and on linux the port name does not change

bendenoz@d9b7c281d71bc981a75bbd4fef5297ad193189a2

/Benjamin

**Comment by andreskwan** [comment]
![screenshot_2014-08-06_10_51_28](https://cloud.githubusercontent.com/assets/2591072/3829584/d1f630a0-1d81-11e4-87ce-dc02795ddcb9.png)
Hi! 
This works for me, I hope this helps
![screenshot_2014-08-06_10_41_33](https://cloud.githubusercontent.com/assets/2591072/3829447/d69e314e-1d80-11e4-80f8-bbf15a80a549.png)
![screenshot_2014-08-06_10_45_27](https://cloud.githubusercontent.com/assets/2591072/3829452/de31a350-1d80-11e4-8014-6593b615e87e.png)
